const storageKey = 'cell-factory-ai-v3';
const oceanDrops = ['磷脂質','脂肪酸','磷酸鹽','核苷酸','胺基酸','ATP','葡萄糖','氧氣','好氧細菌'];
const initial = { inventory:{}, board:Array(25).fill(null), achievements:[] };
let state = JSON.parse(localStorage.getItem(storageKey) || 'null') || structuredClone(initial);
let selected = null, timer = null;
const $ = s => document.querySelector(s);
function save(){localStorage.setItem(storageKey,JSON.stringify(state))}
function add(name,n=1){state.inventory[name]=(state.inventory[name]||0)+n}
function achievement(id,title){if(!state.achievements.includes(id)){state.achievements.push(id);notify(`成就解鎖：${title}`)}}
function status(){if(state.achievements.includes('division'))return ['可分裂細胞','第一次細胞分裂已完成。'];if(state.achievements.includes('organelle'))return ['具胞器細胞','內共生帶來新的能量工廠。'];if(state.achievements.includes('cell'))return ['原始細胞','已經具備可演化的細胞系統。'];return ['DNA','DNA 本身不是細胞；探勘海洋並讓 AI 協助規劃下一步。']}
function render(){const [name,hint]=status();$('#lifeState').textContent=name;$('#stateHint').textContent=hint;$('#statusOrb span').textContent=name==='DNA'?'DNA':'CELL';const inv=$('#inventory');inv.innerHTML='';Object.entries(state.inventory).sort().forEach(([name,n])=>{const b=document.createElement('button');b.className='material '+(selected===name?'selected':'');b.innerHTML=`${name}<b>×${n}</b>`;b.onclick=()=>{selected=selected===name?null:name;render()};inv.append(b)});$('#inventoryCount').textContent=`${Object.keys(state.inventory).length} 種物質`;$('#selectionText').textContent=selected?`已選：${selected}`:'尚未選擇物質';const bench=$('#workbench');bench.innerHTML='';state.board.forEach((item,i)=>{const el=document.createElement('button');el.className='cell '+(item?'filled':'');el.textContent=item||'+';el.onclick=()=>place(i);bench.append(el)});renderAchievements();save()}
function renderAchievements(){const list=$('#achievements');if(!list)return;const defs=[['membrane','膜的起源','建立界線與內外環境'],['molecule','分子組裝','產生可用的生物分子'],['cell','細胞化','形成原始細胞系統'],['organelle','內共生','取得胞器'],['division','生命延續','完成第一次細胞分裂']];list.innerHTML=defs.map(([id,t,d])=>`<div class="achievement ${state.achievements.includes(id)?'unlocked':''}"><span>${state.achievements.includes(id)?'✓':'○'}</span><div><b>${t}</b><small>${d}</small></div></div>`).join('')}
function notify(t){$('#reactionLog').textContent=t}
function place(i){if(state.board[i]){add(state.board[i]);state.board[i]=null;render();return}if(!selected||!state.inventory[selected])return;if(--state.inventory[selected]===0)delete state.inventory[selected];state.board[i]=selected;render()}
function receive(item){add(item);const d=document.createElement('div');d.className='incoming-item';d.textContent=`+ ${item}`;$('#incoming').append(d);setTimeout(()=>d.remove(),1400);render()}
function startDrops(){if(timer)return;let left=10;$('#nextDrop').textContent=`下一批物資：${left} 秒`;timer=setInterval(()=>{left--;$('#nextDrop').textContent=`下一批物資：${left} 秒`;if(left===0){receive(oceanDrops[Math.floor(Math.random()*oceanDrops.length)]);left=10}},1000)}
function explore(){const b=$('#exploreButton');b.disabled=true;setTimeout(()=>{if(!state.achievements.includes('first-exploration')){add('磷脂質',2);achievement('first-exploration','海洋探勘');notify('發現磷脂質。把材料放上合成台，讓 AI 判斷可行的演化途徑。');startDrops()}else{receive(oceanDrops[Math.floor(Math.random()*oceanDrops.length)]);notify('探勘隊帶回一份原始海洋材料。')}b.disabled=false;render()},650)}
async function askAI(items){const cfg=JSON.parse(localStorage.getItem('cell-factory-api')||'{}');if(!cfg.endpoint||!cfg.key)throw new Error('尚未設定 AI API');const prompt=`你是「細胞工廠」的生物學導引員。玩家目前生命階段：${status()[0]}；已解鎖：${state.achievements.join('、')||'無'}。合成台材料：${items.join('、')}。\n請依真實生物學判斷最佳的下一步。你可以提出化學／生化組裝、發現、內共生或細胞分裂，但絕不可把不可能的反應說成成功。粒線體等胞器必須視為吞噬後的長期內共生，不能當成普通化合物。若材料不足，使用 partial，建議需要探勘的材料，不要懲罰玩家。\n只回傳 JSON：{"verdict":"success|partial","mode":"molecule|membrane|cell|endosymbiosis|division|discovery","product":"產物或事件名稱","explanation":"繁體中文、55字內","keep_host":true|false,"needed":"可選，缺少的條件"}`;const res=await fetch(cfg.endpoint,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${cfg.key}`},body:JSON.stringify({model:cfg.model||'gpt-4.1-mini',messages:[{role:'system',content:'只輸出有效 JSON。嚴格遵守使用者訊息中的生物學限制。'},{role:'user',content:prompt}],temperature:.35,response_format:{type:'json_object'}})});if(!res.ok)throw new Error(`API 回應失敗（${res.status}）`);const data=await res.json();return JSON.parse(data.choices[0].message.content)}
function unlockFrom(result){if(result.mode==='membrane')achievement('membrane','膜的起源');if(['molecule','discovery'].includes(result.mode))achievement('molecule','分子組裝');if(result.mode==='cell')achievement('cell','細胞化');if(result.mode==='endosymbiosis')achievement('organelle','內共生');if(result.mode==='division')achievement('division','生命延續')}
async function synthesize(){const items=state.board.filter(Boolean);if(!items.length)return notify('請先將材料放到合成台。');const btn=$('#synthesizeButton');btn.disabled=true;notify('AI 正在檢視反應條件、演化機制與材料限制……');await new Promise(r=>setTimeout(r,900));try{const result=await askAI(items);if(result.verdict!=='success'){notify(`條件尚不足：${result.explanation}${result.needed?` 建議探勘：${result.needed}。`:''} 原料已保留。`);btn.disabled=false;return}state.board=Array(25).fill(null);if(result.product)add(result.product);if(result.keep_host&&items.includes('原始細胞'))add('原始細胞');unlockFrom(result);notify(`${result.mode==='endosymbiosis'?'內共生事件':'AI 判定成功'}：${result.product}。${result.explanation}`)}catch(e){notify(`${e.message}。點右上角 AI，填入 OpenAI 相容 API 後即可開始由 AI 判定；材料已保留。`)}btn.disabled=false;render()}
$('#exploreButton').onclick=explore;$('#clearButton').onclick=()=>{state.board.filter(Boolean).forEach(x=>add(x));state.board=Array(25).fill(null);render()};$('#synthesizeButton').onclick=synthesize;$('#resetButton').onclick=()=>{if(confirm('要重新開始這座細胞工廠嗎？')){localStorage.removeItem(storageKey);location.reload()}};$('#apiButton').onclick=()=>{const c=JSON.parse(localStorage.getItem('cell-factory-api')||'{}');$('#apiEndpoint').value=c.endpoint||'https://api.openai.com/v1/chat/completions';$('#apiKey').value=c.key||'';$('#apiModel').value=c.model||'gpt-4.1-mini';$('#apiDialog').showModal()};$('#apiForm').addEventListener('submit',e=>{e.preventDefault();localStorage.setItem('cell-factory-api',JSON.stringify({endpoint:$('#apiEndpoint').value.trim(),key:$('#apiKey').value.trim(),model:$('#apiModel').value.trim()}));$('#apiDialog').close();notify('AI 導引員已設定。把材料放上合成台後開始判定。')});render();if(state.achievements.includes('first-exploration'))startDrops();
